language: elixir

env:
  - MIX_ENV=test

elixir:
  - 1.5

otp_release:
  - 20.0

sudo: true

services:
  - docker
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - yarn global add chromedriver
  - mix compile
  - mix ecto.setup
  - mix test

script: ./config/ci/shipit.sh
